apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/user-service

images:
  - name: jendyjasper/user-service
    newTag: 6.0.0

patches:
  - target:
      kind: Rollout
      name: user-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/6/value
        value: development
