apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: user-service-cert
spec:
  secretName: user-service-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: user-service.local
  dnsNames:
  - user-service.local