apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-user-to-database
  namespace: database
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["user-service", "istio-system"]

---
#Enforce STRICT mTLS for database namespace
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: strict-db-traffic
  namespace: database
spec:
  mtls:
    mode: STRICT