apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - configmap.yaml
  - persistent-volume-claim.yaml
  - sealed-secret.yaml
  - statefulset.yaml
  - service.yaml

commonLabels:
  app: postgres