apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
  - persistent-volume-claim.yaml
  - configmap.yaml
  - sealed-secret.yaml
  - authorizationpolicy.yaml