apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
    environment: production
    istio-injection: enabled 
    pod-security.kubernetes.io/enforce: baseline
  annotations:
    networking.istio.io/exportTo: "."
    topology.istio.io/network: kind