---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-secret
  namespace: database
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAST0WrS3x2u+DYSzvnoAh/GKbNUjRZ+hd/P8TkFeXJw69O6XtaQrv7Mzvfngy+HZXtqnp2VSfAD4oabODsWnchQlV4ik+nTfaEXWljaBe6JLLgRoZel2jXouDkY/CHFZVsvxVSeY6hG6G4YZIopcHUD9TJR/lSPOqnU2PIGU99u7pwVuQrZu7e0KaHNeH2dU69LoXiLyLkj1R1VBjIRz32VNV2k+tA/fJTfFQlUtSAxJE67ForFW6NleBoXzHjLBGit04ZgChgRq94QJQKwxxBrk2zq0iKhuk3+x62c/zEGcNE3vY4YMIzIrU22sixdLqbzBu3Yf967+xnEoMEen31XJpDBnQN2019INdoHCA4BTEZY9KOFnIgkUh05CioB9A9Xpcgp1/RWgcXiYdpQ3QpQqFkbhGuBSrUOn/NuU27S2UgGPn/UaAVswASJ0TZLXG3Gv3tCMtIlUCbQW0GH9fjE9kwB4uo8yOr6bmvK4SHpjwpo1EYSILKUs5Ky5aL0A6pJnw2uoKGspwYCWp1fotJ8nFjBGBA7WNl9rSliq5AgNKeIKK5+LxSI2elt+/cDGMfHxfz9RRlFUbCEtxV6McmWRAjj9W+OnDWGTQNFE+1BXk8ZMsoMeQXD+8ZXmdIR8n6Yjpo1M2H7ljJgnBGFpNB/JNPM6CzlHg9Bqe0xws4a9SCHNE7CWqshyJE70nmMUN+AQrsGo9bI02XFAap6O/lJ38QZ+g=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-secret
      namespace: database
    type: Opaque
