---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-secret
  namespace: database
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAu+5243oh7Ts1wIMqzp3ycUozNEs2PDCmUmWLx5/DmhAsVPcMTFUzxLLlFlYFNfdYO/ocr33NJ7VDfWBARovtvvt2bpxi4cdtng24vFeThnfM4l9YAYKUqmstRaSfT7GPl9R/eJUVDQkDZgg9w045SRX1zPWpVdd231oGoWCU1S8vzEO0CCHnIZFMRA9ruWYGn9KZY2b7s2IfGTju0HTQOUNdQ4/0AXewx/oAM/K76gIG0L+pLeO0q1XgE94BTKiZFiU/lx0c/RKgGIuuFgypq1I9Y8uRejj9kJdEGXThekuwbOM1Uj28tQeljLVn7NfPrP8ZIZI9Tifo1udlKZu5+DyhSvUkkHZIe0YynYqDRII3n1qaFyBmcjDjbtPj6di8+5MXMeUE8hsyTId/aO5/eB2X9vsBrHp8XVxe8nzAdjJbxIhcNm/42loovtE8KL5D0FblLayUR2vpHXC7wxlmTh+26dmVh1Z3a9KhpXZFsV9cPJbSQmv6WLpcLLksBs9YndDJ/KG//NR4vxYRSPcKUt94fnz2E7oS+sfBPYZJpa4Y41pidD0hY6y4YRxiBxWRfhHHMgvAdo++udWtxZE3RPURevuNHYuz4uYkIoR1MJwNIoYmp63/0w0MogVIJO1iYOnaSUG2aovvvRepRByCEAES7cE81/ObtK4Tgmf8QaneWQNWvSmTG0esCb9ONmtVJ+6xQpoQzfvvlh2p7jzyFEoe0Muk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-secret
      namespace: database
    type: Opaque
