apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-sealed-secret
  namespace: database
spec:
  encryptedData:
    # This will be replaced with actual encrypted value
    POSTGRES_PASSWORD: AgCCeN7mGS...(replace with your encrypted value)
  template:
    metadata:
      name: postgres-secret
      namespace: database
    type: Opaque