---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-secret
  namespace: database
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB9hkDA2rjZU/VPXRPbrKIOIP0f1T1Y4pdu/Zne+6NlxZwehKoIoxtzNSuKYKwaqy1OWNMJRYhZ4LhLJONks18BNZ80/H/LIgyH1jwf6PBFLJ47ZENXPgfXXRdet/iTNyG4Bcr5LNxc3cIbjxLMQKJIUzMefzdwAEmlZWMP2F0/6aO7e2Bb0wSikSyX07TSzOo/ql7kG0Hqfd4TD7Autejk6uDoSyPv7wkwXJuoJhrWPYFIFVEeWAdV8eE8SxI5g3x+dadGcGDSGxd55rpjiiEJQINoBDqUIJIxctBDsF24YwXK/KD42rk5SPmlxQcBLyWx71V85bpz4HFXmarkDYB4W4uo7UtJW/oxVaxzXX0V0wbZWsqz777O4G4C7cWL1b46qvENWZ8IDzIvOUX/+NtyreD2g9UsAUza3gIt4zOLUg7bccKs2oI88frZbCqHOPKJ3Bezt0YFAPK6BCqtmZN3jeygAEguFIIzWkJnXdt/SKatrZ/nsjebvrhVZM+rMgc5mIdapde5Dhsc6eOEhXfi9571bSwPOwRrfHZVXceCIA7vibK0CpFFvdwJCNk3whMssVCM84yZ1Ii4XPsYCXoqVndh5p+z65+0h/FpMFcZ6OyVgtHN+EVKSSARS1sycWCsSZgcXX2FcpQhrKiUCmyo4suiVeH3vQ55teBQbI+WJfklKiT7kgOLwsosH4zaQ9a+cCapsxh9JX7J/f64Cg9srfaUnhA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-secret
      namespace: database
    type: Opaque
