loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      directory: /data/loki
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: standard
  auth_enabled: false

service:
  type: ClusterIP
  port: 3100

gateway:
  enabled: true
  ingress:
    enabled: false

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      maxLines: 1000
      searchNamespace: ALL
  serviceMonitor:
    enabled: false

# Promtail configuration (send logs to Loki)
promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
