loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      directory: /var/loki
  persistence:
    enabled: true
    storageClassName: standard
    size: 1Gi
  auth_enabled: false

deploymentMode: SingleBinary

service:
  type: ClusterIP
  port: 3100

gateway:
  enabled: true

# Promtail setup to push logs
promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push

# Grafana datasource auto-registration
grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      searchNamespace: ALL
