loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  auth_enabled: false
  singleBinary:
    enabled: true

read:
  enabled: false
write:
  enabled: false
backend:
  enabled: false

persistence:
  enabled: true
  storageClassName: standard
  size: 1Gi

service:
  type: ClusterIP
  port: 3100

gateway:
  enabled: true

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      searchNamespace: ALL