loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: standard
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
    auth_enabled: false
  fullnameOverride: "loki"

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
    - url: http://loki-stack-gateway.logging.svc.cluster.local/loki/api/v1/push

gateway:
  enabled: true

grafana:
  enabled: false

nginx:
  enabled: false

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

global:
  imagePullSecrets: []