apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  labels:
    type: infrastructure
    team: platform
spec:
  project: default
  sources:
    - repoURL: https://github.com/JendyJasper/cm-demo.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.23.1
      helm:
        releaseName: istio-base
        valueFiles:
          - $values/service-mesh/istio-base-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
