apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.22.0
    helm:
      releaseName: loki
      valueFiles:
        - $values/monitoring/loki-values.yaml
  sources:
    - repoURL: https://github.com/JendyJasper/cm-demo.git
      targetRevision: main
      ref: values
