apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  labels:
    app: postgresql
    team: platform
spec:
  project: default
  source:
    repoURL: https://github.com/JendyJasper/cm-demo.git
    targetRevision: HEAD
    path: k8s/base/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true