meshConfig:
  enableTracing: true
  accessLogFile: /dev/stdout
  enablePrometheusMerge: true
  defaultConfig:
    holdApplicationUntilProxyStarts: true
    concurrency: 2

pilot:
  autoscaleEnabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  enableProtocolSniffingForOutbound: true
  enableProtocolSniffingForInbound: true
  resource_limits_env: false 
  resourcesEnv: false 


# Enable ingress gateway for internal traffic
gateways:
  istio-ingressgateway:
    enabled: false


global:
  proxy:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

telemetry:
  v2:
    enabled: true
    prometheus:
      enabled: true