service:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    name: http2
    nodePort: 31380
  - port: 443
    targetPort: 8443
    name: https
    nodePort: 31390
  - port: 31400
    targetPort: 15443
    name: tls
    nodePort: 31400

# Resource optimization
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Autoscaling
autoscaleEnabled: true
autoscaleMin: 1
autoscaleMax: 3

# Enable Prometheus metrics
env:
  PILOT_CACHE_SQUASH: "true"
  PILOT_ENABLE_EDS_FOR_HEADLESS_SERVICES: "true"