apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
- security-policies.yaml
- user-service-gateway.yaml
- user-service-destinationrule.yaml
- user-service-virtualservice.yaml
- security/mesh-security.yaml