
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: base

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    environment: base

---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  labels:
    name: argo-rollouts
    environment: base
    