apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
    environment: base
---
apiVersion: v1
kind: Namespace
metadata:
  name: user-service
  labels:
    name: user-service
    environment: base

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: base
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    name: ingress
    environment: base
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
    environment: base

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    environment: base

---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  labels:
    name: argo-rollouts
    environment: base
    